services:
    web:
        container_name: web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "9000:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - online_store-app  # Ensure PHP-FPM is started before Nginx
        networks:
            - online_store-network  # Connect to the custom network

    online_store-app:
        container_name: online_store-app
        build: .  # Build from the Dockerfile
        depends_on:
            - store_db
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
        networks:
            - online_store-network  # Connect to the custom network

    store_db:
        container_name: online_store_db
        image: mysql:8  # Use MySQL image
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: online_store_db  # Create a database named 'laravel'
            MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
        volumes:
            - ./online_store_db:/var/lib/mysql  # 'online_store_db' mutlaq yo'l bo'lishi kerak

        networks:
            - online_store-network  # Connect to the custom network

    online_store-node:
        container_name: online_store-node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - online_store-network
        command: bash -c "npm install && npm run build"

# Define the custom network
networks:
    online_store-network:  # Create a custom network named 'laravel-network'
        driver: bridge

# Define the volume for MySQL data persistence
volumes:
    online_store_db:
